/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javadatabase;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author Ahmad Yusuf
 */
public class MainFrame extends javax.swing.JFrame {

    DefaultTableModel modelMahasiswa;
    boolean isEdit;

    private MahasiswaDAO dao = new MahasiswaDAO();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        BiayaKuliah_txt.setEditable(false);
        setupAutoHitungBiaya();
        String[] kolom = {"ID", "NIM", "Nama", "Tahun Masuk", "Jenis Mahasiswa", "SKS", "Biaya"};
        modelMahasiswa = new DefaultTableModel(kolom, 0);
        tblMahasiswa.setModel(modelMahasiswa);

        tblMahasiswa.getSelectionModel().addListSelectionListener(e -> {
            int row = tblMahasiswa.getSelectedRow();
            if (row != -1) {
                txtNama.setText(modelMahasiswa.getValueAt(row, 2).toString());
                txtNim.setText(modelMahasiswa.getValueAt(row, 1).toString());
                txtTahunMasuk.setText(modelMahasiswa.getValueAt(row, 3).toString());

                // Tambahan:
                JenisMahasiswa_cmbBox.setSelectedItem(modelMahasiswa.getValueAt(row, 4).toString());
                JumlahSks_txt.setText(modelMahasiswa.getValueAt(row, 5).toString());
                BiayaKuliah_txt.setText(
                        modelMahasiswa.getValueAt(row, 6).toString()
                );
            }
        });

        isEdit = false;
        loadData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNama = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblNim = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        lblTahunMasuk = new javax.swing.JLabel();
        txtTahunMasuk = new javax.swing.JTextField();
        btnCSV = new javax.swing.JButton();
        JenisMahasiswa_lbl = new javax.swing.JLabel();
        JenisMahasiswa_cmbBox = new javax.swing.JComboBox<>();
        JumlahSKS_lbl = new javax.swing.JLabel();
        BiayaKuliah_lbl = new javax.swing.JLabel();
        JumlahSks_txt = new javax.swing.JTextField();
        BiayaKuliah_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit.setText("Tambah");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNama.setText("Nama:");

        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblMahasiswa.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblMahasiswa);

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblNim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNim.setText("NIM:");

        lblTahunMasuk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTahunMasuk.setText("Tahun Masuk:");

        txtTahunMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunMasukActionPerformed(evt);
            }
        });

        btnCSV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCSV.setText("Upload CSV");
        btnCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSVActionPerformed(evt);
            }
        });

        JenisMahasiswa_lbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JenisMahasiswa_lbl.setText("Jenis Mahasiswa:");

        JenisMahasiswa_cmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Beasiswa", "Internasional" }));
        JenisMahasiswa_cmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisMahasiswa_cmbBoxActionPerformed(evt);
            }
        });

        JumlahSKS_lbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JumlahSKS_lbl.setText("Jumlah SKS:");

        BiayaKuliah_lbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BiayaKuliah_lbl.setText("Biaya Kuliah:");

        JumlahSks_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahSks_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCSV))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblTahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JumlahSKS_lbl)
                                    .addComponent(BiayaKuliah_lbl)
                                    .addComponent(JenisMahasiswa_lbl)
                                    .addComponent(lblNim, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNim, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtTahunMasuk)
                                .addComponent(txtNama))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JenisMahasiswa_cmbBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 119, Short.MAX_VALUE)
                                .addComponent(BiayaKuliah_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JumlahSks_txt, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTahunMasuk)
                    .addComponent(txtTahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JenisMahasiswa_lbl)
                    .addComponent(JenisMahasiswa_cmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JumlahSKS_lbl)
                    .addComponent(JumlahSks_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BiayaKuliah_lbl)
                    .addComponent(BiayaKuliah_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnCSV))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        insert(); // simpan ke database

        txtNama.setText("");
        txtNim.setText("");
        txtTahunMasuk.setText("");
        JenisMahasiswa_cmbBox.setSelectedIndex(0);
        JumlahSks_txt.setText("");
        BiayaKuliah_txt.setText("");

        loadData(); // refresh tabel dari DB

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int row = tblMahasiswa.getSelectedRow();
        if (row == -1) {
            return;
        }

        int id = (int) modelMahasiswa.getValueAt(row, 0);
        dao.delete(id);
        loadData();


    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = tblMahasiswa.getSelectedRow();
        if (row == -1) {
            return;
        }

        Mahasiswa mhs = buatObjekMahasiswa();
        mhs.setId((int) modelMahasiswa.getValueAt(row, 0));

        dao.update(mhs);
        loadData();

    }//GEN-LAST:event_btnEditActionPerformed

    private void txtTahunMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTahunMasukActionPerformed

    private void btnCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSVActionPerformed
        // TODO add your handling code here:
        uploadCSV();
    }//GEN-LAST:event_btnCSVActionPerformed

    private void JenisMahasiswa_cmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisMahasiswa_cmbBoxActionPerformed
        // TODO add your handling code here:
        hitungDanTampilkanBiaya();

    }//GEN-LAST:event_JenisMahasiswa_cmbBoxActionPerformed

    private void JumlahSks_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahSks_txtActionPerformed
        // TODO add your handling code here:
        hitungDanTampilkanBiaya();
    }//GEN-LAST:event_JumlahSks_txtActionPerformed

    private void insert() {

        try {
            Mahasiswa mhs = buatObjekMahasiswa();
            dao.insert(mhs);
            loadData();
        } catch (Exception e) {
            System.out.println("Insert error: " + e.getMessage());
        }

    }

    private void loadData() {
        //select * from mahasiswa

        modelMahasiswa.setRowCount(0);

        for (Mahasiswa mhs : dao.getAll()) {
            Object[] row = {
                mhs.getId(),
                mhs.getNim(),
                mhs.getNama(),
                mhs.getTahunMasuk(),
                mhs.getjenis(),
                mhs.getsks(),
                formatRupiah(mhs.hitungBiaya())
            };
            modelMahasiswa.addRow(row);

        }

    }

    private void uploadCSV() {
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        int result = fc.showOpenDialog(this);

        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {

            java.io.File file = fc.getSelectedFile();

            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(file))) {

                String line;
                int success = 0, failed = 0;

                Connection conn = DbConnection.connect();
                String sql = "INSERT INTO mahasiswa (nim, nama, tahunmasuk, jenis, sks, biaya) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement ps = conn.prepareStatement(sql);

                while ((line = br.readLine()) != null) {

                    if (line.toLowerCase().contains("nim")) {
                        continue; // skip header
                    }

                    String[] d = line.split("[,;]");

                    if (d.length < 5) {
                        failed++;
                        continue;
                    }

                    String nim = d[0].trim();
                    String nama = d[1].trim();
                    int tahun = Integer.parseInt(d[2].trim());
                    String jenis = d[3].trim();
                    int sks = Integer.parseInt(d[4].trim());

                    Mahasiswa mhs;

                    switch (jenis) {
                        case "Beasiswa":
                            mhs = new MahasiswaBeasiswa(nama, nim, tahun, sks);
                            break;
                        case "Internasional":
                            mhs = new MahasiswaInternasional(nama, nim, tahun, sks);
                            break;
                        default:
                            mhs = new MahasiswaReguler(nama, nim, tahun, sks);
                    }

                    dao.insert(mhs);
                    success++;
                }

                conn.close();
                loadData();

                System.out.println("Upload selesai! Berhasil: " + success + " | Gagal: " + failed);

            } catch (Exception e) {
                System.out.println("CSV Error: " + e.getMessage());
            }
        }

    }

    private void hitungDanTampilkanBiaya() {
        try {
            Mahasiswa mhs = buatObjekMahasiswa();
            long biaya = mhs.hitungBiaya();
            BiayaKuliah_txt.setText(formatRupiah(biaya));
        } catch (Exception e) {
            // input belum lengkap, abaikan
        }
    }

    private Mahasiswa buatObjekMahasiswa() {
        String nama = txtNama.getText();
        String nim = txtNim.getText();
        int tahun = Integer.parseInt(txtTahunMasuk.getText());
        int sks = Integer.parseInt(JumlahSks_txt.getText());
        String jenis = JenisMahasiswa_cmbBox.getSelectedItem().toString();

        switch (jenis) {
            case "Beasiswa":
                return new MahasiswaBeasiswa(nama, nim, tahun, sks);
            case "Internasional":
                return new MahasiswaInternasional(nama, nim, tahun, sks);
            default:
                return new MahasiswaReguler(nama, nim, tahun, sks);
        }
    }

    private void setupAutoHitungBiaya() {
        JumlahSks_txt.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                hitungDanTampilkanBiaya();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                hitungDanTampilkanBiaya();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                hitungDanTampilkanBiaya();
            }
        });
    }

    private String formatRupiah(long nilai) {
        NumberFormat rupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        rupiah.setMaximumFractionDigits(0);
        rupiah.setMinimumFractionDigits(0);
        return rupiah.format(nilai);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BiayaKuliah_lbl;
    private javax.swing.JTextField BiayaKuliah_txt;
    private javax.swing.JComboBox<String> JenisMahasiswa_cmbBox;
    private javax.swing.JLabel JenisMahasiswa_lbl;
    private javax.swing.JLabel JumlahSKS_lbl;
    private javax.swing.JTextField JumlahSks_txt;
    private javax.swing.JButton btnCSV;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNim;
    private javax.swing.JLabel lblTahunMasuk;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtTahunMasuk;
    // End of variables declaration//GEN-END:variables

}
